repos:
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.4.0  
    hooks:
      - id: sqlfluff-lint
        name: sqlfluff lint (models)
        entry: sqlfluff lint models/
        language: system
        types: [sql]