name: 'Bolt'
version: '1.0'
profile: 'Bolt'
config-version: 2

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
analysis-paths: ["analysis"]
snapshot-paths: ["snapshots"]
target-path: "target"
clean-targets: ["target", "dbt_modules"]

seeds:
  Bolt:
    +schema: public

models:
  Bolt:
    +materialized: view
    staging:
      +materialized: view
    marts:
      +materialized: table
    facts:
      +materialized: table
